import type { RuleSet } from "./types.js";

export const defaultRuleSet: RuleSet = {
  version: "1.0.0",
  rules: [
    { latin: "aa", assamese: "আ", kind: "vowel", matra: "া" },
    { latin: "ii", assamese: "ঈ", kind: "vowel", matra: "ী" },
    { latin: "uu", assamese: "ঊ", kind: "vowel", matra: "ূ" },
    { latin: "oi", assamese: "ঐ", kind: "vowel", matra: "ৈ" },
    { latin: "ou", assamese: "ঔ", kind: "vowel", matra: "ৌ" },
    { latin: "ri", assamese: "ঋ", kind: "vowel", matra: "ৃ" },
    { latin: "a", assamese: "অ", kind: "vowel", matra: "া" },
    { latin: "i", assamese: "ই", kind: "vowel", matra: "ি" },
    { latin: "u", assamese: "উ", kind: "vowel", matra: "ু" },
    { latin: "e", assamese: "এ", kind: "vowel", matra: "ে" },
    { latin: "o", assamese: "ও", kind: "vowel", matra: "ো" },
    { latin: "kh", assamese: "খ", kind: "consonant" },
    { latin: "gh", assamese: "ঘ", kind: "consonant" },
    { latin: "ng", assamese: "ঙ", kind: "consonant" },
    { latin: "ch", assamese: "ছ", kind: "consonant" },
    { latin: "jh", assamese: "ঝ", kind: "consonant" },
    { latin: "nj", assamese: "ঞ", kind: "consonant" },
    { latin: "ny", assamese: "ঞ", kind: "consonant" },
    { latin: "Th", assamese: "ঠ", kind: "consonant" },
    { latin: "Dh", assamese: "ঢ", kind: "consonant" },
    { latin: "th", assamese: "থ", kind: "consonant" },
    { latin: "dh", assamese: "ধ", kind: "consonant" },
    { latin: "ph", assamese: "ফ", kind: "consonant" },
    { latin: "bh", assamese: "ভ", kind: "consonant" },
    { latin: "sh", assamese: "শ", kind: "consonant" },
    { latin: "Sh", assamese: "ষ", kind: "consonant" },
    { latin: "rr", assamese: "ড়", kind: "consonant" },
    { latin: "rh", assamese: "ঢ়", kind: "consonant" },
    { latin: "gy", assamese: "জ্ঞ", kind: "consonant" },
    { latin: "kS", assamese: "ক্ষ", kind: "consonant" },
    { latin: "x", assamese: "ক্ষ", kind: "consonant" },
    { latin: "k", assamese: "ক", kind: "consonant" },
    { latin: "g", assamese: "গ", kind: "consonant" },
    { latin: "c", assamese: "চ", kind: "consonant" },
    { latin: "j", assamese: "জ", kind: "consonant" },
    { latin: "T", assamese: "ট", kind: "consonant" },
    { latin: "D", assamese: "ড", kind: "consonant" },
    { latin: "N", assamese: "ণ", kind: "consonant" },
    { latin: "t", assamese: "ত", kind: "consonant" },
    { latin: "d", assamese: "দ", kind: "consonant" },
    { latin: "n", assamese: "ন", kind: "consonant" },
    { latin: "p", assamese: "প", kind: "consonant" },
    { latin: "b", assamese: "ব", kind: "consonant" },
    { latin: "m", assamese: "ম", kind: "consonant" },
    { latin: "y", assamese: "য", kind: "consonant" },
    { latin: "r", assamese: "ৰ", kind: "consonant" },
    { latin: "l", assamese: "ল", kind: "consonant" },
    { latin: "w", assamese: "ৱ", kind: "consonant" },
    { latin: "s", assamese: "স", kind: "consonant" },
    { latin: "S", assamese: "শ", kind: "consonant" },
    { latin: "h", assamese: "হ", kind: "consonant" },
    { latin: "v", assamese: "ভ", kind: "consonant" },
    { latin: "f", assamese: "ফ", kind: "consonant" },
    { latin: "z", assamese: "জ", kind: "consonant" },
    { latin: "q", assamese: "ক", kind: "consonant" },
    { latin: "||", assamese: "॥", kind: "special" },
    { latin: "|", assamese: "।", kind: "special" },
    { latin: "~", assamese: "্", kind: "special" },
    { latin: "`", assamese: "\u200D", kind: "special" },
    { latin: "M", assamese: "ঁ", kind: "special" },
    { latin: "H", assamese: "ঃ", kind: "special" },
    { latin: "0", assamese: "০", kind: "numeral" },
    { latin: "1", assamese: "১", kind: "numeral" },
    { latin: "2", assamese: "২", kind: "numeral" },
    { latin: "3", assamese: "৩", kind: "numeral" },
    { latin: "4", assamese: "৪", kind: "numeral" },
    { latin: "5", assamese: "৫", kind: "numeral" },
    { latin: "6", assamese: "৬", kind: "numeral" },
    { latin: "7", assamese: "৭", kind: "numeral" },
    { latin: "8", assamese: "৮", kind: "numeral" },
    { latin: "9", assamese: "৯", kind: "numeral" }
  ]
};
